name: PR CI (fast)

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Unit tests
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONPATH: ${{ github.workspace }}
          API_KEY: test-key
        run: |
          python -m pytest --cov=serving_app --cov-report=term-missing

  smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps only
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Boot API (no training for speed)
        env:
          API_KEY: test-key
        run: |
          set -euo pipefail
          uvicorn serving_app.main:app --host 127.0.0.1 --port 8011 >/tmp/uvicorn.log 2>&1 &
          echo $! > /tmp/uvicorn.pid
          for i in {1..40}; do
            if curl -sf http://127.0.0.1:8011/health >/dev/null; then
              echo "API is up"
              exit 0
            fi
            sleep 0.5
          done
          echo "API failed to start"; cat /tmp/uvicorn.log || true; exit 1

      - name: Shutdown
        if: always()
        run: |
          [ -f /tmp/uvicorn.pid ] && kill "$(cat /tmp/uvicorn.pid)" || true
          sleep 1
          pkill -f "uvicorn" || true

      - name: Upload logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: uvicorn-logs
          path: /tmp/uvicorn.log

