name: CI
on: [push, pull_request]

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Unit tests
        env:
          PYTHONDONTWRITEBYTECODE: 1
        run: |
          python -m pytest --cov=serving_app --cov-report=term-missing

      - name: Train model
        run: python -m training.train

      - name: Boot API
        env:
          API_KEY: test-key
        run: |
          set -euo pipefail
          uvicorn serving_app.main:app --host 127.0.0.1 --port 8011 >/tmp/uvicorn.log 2>&1 &
          echo $! > /tmp/uvicorn.pid
          # Wait up to 20s for health
          for i in {1..40}; do
            if curl -sf http://127.0.0.1:8011/health >/dev/null; then
              echo "API is up"
              exit 0
            fi
            sleep 0.5
          done
          echo "API failed to start. Logs:"
          cat /tmp/uvicorn.log || true
          exit 1

      - name: Predict smoke
        env:
          API_KEY: test-key
        run: |
          set -euo pipefail
          RESP=$(curl -s -X POST "http://127.0.0.1:8011/predict" \
            -H 'Content-Type: application/json' \
            -H "x-api-key: ${API_KEY}" \
            -d '{"features":[5.1,3.5,1.4,0.2], "return_proba":true}')
          echo "$RESP" | jq .
          # Basic shape checks
          echo "$RESP" | jq -e 'has("prediction") and has("proba") and has("latency_ms")' >/dev/null

      - name: Shutdown
        if: always()
        run: |
          [ -f /tmp/uvicorn.pid ] && kill $(cat /tmp/uvicorn.pid) || true
          sleep 1
          pkill -f "uvicorn" || tr

