name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - run: pip install -r requirements.txt
      - name: Train model
        run: python -m training.train
      - name: Boot API
        env: { API_KEY: "" }
        run: |
          uvicorn serving_app.main:app --host 127.0.0.1 --port 8011 &
          echo $! > uvicorn.pid
          for i in {1..40}; do
            curl -sf http://127.0.0.1:8011/health && break
            sleep 0.5
          done
      - name: Predict smoke
        run: |
          curl -s -X POST http://127.0.0.1:8011/predict \
            -H 'Content-Type: application/json' \
            -d '{"features":[5.1,3.5,1.4,0.2], "return_proba":true}' | python -m json.tool
      - name: Shutdown
        if: always()
        run: kill $(cat uvicorn.pid) || true
