name: Release (Build & Push Image)

on:
  push:
    tags:
      - 'v*'        # e.g. v0.1.0
  workflow_dispatch:

permissions:
  contents: read
  packages: write    # required for GHCR

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute image name & tag
        id: prep
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lc=$REPO_LC" >> $GITHUB_OUTPUT
          TAG="${{ github.ref_name }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.prep.outputs.repo_lc }}:${{ steps.prep.outputs.tag }}
            ghcr.io/${{ steps.prep.outputs.repo_lc }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dockerhub:
    if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prep tag
        id: prep
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (Docker Hub)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/serving-app:${{ steps.prep.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/serving-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
